package com.barberconnect.service;

import com.barberconnect.dto.LoginRequest;
import com.barberconnect.dto.RegisterRequest;
import com.barberconnect.dto.AuthResponse;
import com.barberconnect.model.User;
import com.barberconnect.model.BarberProfile;
import com.barberconnect.repository.UserRepository;
import com.barberconnect.repository.BarberProfileRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

@Service
public class AuthService {

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private BarberProfileRepository barberProfileRepository;

    @Autowired
    private PasswordEncoder passwordEncoder;

    public AuthResponse register(RegisterRequest request) {
        if (userRepository.findByEmail(request.getEmail()).isPresent()) {
            throw new RuntimeException("Email already registered");
        }

        User user = new User();
        user.setEmail(request.getEmail());
        user.setPassword(passwordEncoder.encode(request.getPassword()));
        user.setRole(User.Role.valueOf(request.getRole().toUpperCase()));

        user = userRepository.save(user);

        // Create barber profile if registering as barber
        if (request.getRole().equalsIgnoreCase("barber")) {
            BarberProfile barberProfile = new BarberProfile();
            barberProfile.setUser(user);
            barberProfile.setPhone(request.getPhone());
            barberProfile.setGcashNumber(request.getGcashNumber());
            barberProfileRepository.save(barberProfile);
        }

        // Token is generated by Supabase Auth
        return new AuthResponse(null, "User registered successfully", 
            new com.barberconnect.dto.UserResponse(user));
    }

    public AuthResponse login(LoginRequest request) {
        User user = userRepository.findByEmail(request.getEmail())
            .orElseThrow(() -> new RuntimeException("Invalid credentials"));

        if (!passwordEncoder.matches(request.getPassword(), user.getPassword())) {
            throw new RuntimeException("Invalid credentials");
        }

        // Token is generated by Supabase Auth, frontend sends it in requests
        return new AuthResponse(null, "Login successful", 
            new com.barberconnect.dto.UserResponse(user));
    }
}
